[package]
name = "step_3_9"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = {version = "4.3.19", features = ["derive", "cargo"]}
config = "0.12.0"
serde = {version = "1.0.188", features = ["derive"] }
serde_derive = "1.0.188"
