[package]
name = "step_3"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
bytemuck = "1.14.0"
image = "0.24.7"
imagequant = "4.2.1"
pariter = "0.5.1"
reqwest = "0.11.20"
rgb = "0.8.36"
tokio = {version = "1.32.0", features = ["full"]}
url = "2.4.1"
