//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use crate::users_roles;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "role")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub slug: String,
    pub name: Option<String>,
    pub permissions: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::users_roles::Entity")]
    UsersRoles,
}

impl Related<users_roles::Entity> for Entity {
    fn to() -> RelationDef {
        users_roles::Relation::User.def()
    }

    fn via() -> Option<RelationDef> {
        Some(users_roles::Relation::Role.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
